language: csharp
solution: SharePoint.Client.sln
sudo: false
mono:
  - latest
deploy:
  skip_cleanup: true
  provider: script
  script:
    - /bin/sh ./deploy.sh
  on:
    tags: true
branches:
  only:
  - master
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/